variables:
  BASELINE: "1.17"
  MAVEN_DEPLOY_OPTS: "-DinstallAtEnd=true -DdeployAtEnd=true -Dgitlab"
  #MAVEN_DEPLOY_OPTS: ""
  MAVEN_EXTRA_OPTS: "-T8"

include:
  - project: 'ecpnv.devops/infrastructure/pipeline-resources'
    ref: 'prod'
    file:
      - '/build/lib/lifecycle-and-policies.yml'
      - '/build/lib/mvn-deploy-java-8.yml'
      - '/build/pages/antora/generate.yml'
